apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app-container
          image: localhost:5000/portfolio:latest
          ports:
            - containerPort: 80
