apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app-container
          image: localhost:5000/portfolio:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: react
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: ClusterIP
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: react-vs
  namespace: react 
spec:
  host: ikabbash.com
  upstreams:
  - name: react-app-service
    service: react-app-service
    port: 3000
    client-max-body-size: 100m
  routes:
  - path: /
    action:
      pass: react-app-service
