apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: react-vs
  namespace: react 
spec:
  host: ikabbash.com
  upstreams:
  - name: react-app-service
    service: react-app-service
    port: 3000
    client-max-body-size: 100m
  routes:
  - path: /
    action:
      pass: react-app-service
